default: &default
  adapter: postgresql
  username: <%= ENV.fetch("RAILS_DB_USERNAME") %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("RAILS_DB_DEVELOPMENT") %>

test:
  <<: *default
  database: <%= ENV.fetch("RAILS_DB_TEST") %>

production:
  <<: *default
  database: <%= ENV.fetch("RAILS_DB_PRODUCTION") %>
